### ISSUE TITLE
Character viewmodel on non-minimal mode

### ISSUE THREAD

**Issue by laytonleader** [MedicodiBiscotti/biscottiHUD#1]
The character viewmodel on the bottom left corner is messed up on the non - minimal part of the hud. It is all zoomed it like this.

![screenshot](https://cloud.githubusercontent.com/assets/14988943/10298223/7282815a-6baa-11e5-8277-dd91362dded9.png)

**Comment by MedicodiBiscotti** [comment]
Thank you for bringing this to my attention. I tried messing with things that I din't understand. Now I do, and it's fixed. Basically just returned it to the stock values (mostly).
