### ISSUE TITLE
Hello! You need to update info.vdf "ui_version"	"1" to "ui_version"	"2" so the HUD works.

### ISSUE THREAD

**Issue by VandenPlause** [MedicodiBiscotti/biscottiHUD#3]
The info.vdf file should be

"biscottiHUD"
{
	"ui_version"	"2"
}

so it works in game.  Thanks for the work!

**Comment by MedicodiBiscotti** [comment]
I'm a moron man. Thanks for letting me know. It's fixed now. I'm so embarrassed :)
