### ISSUE TITLE
Thermal Thruster's meter overlaps the Phlogs

### ISSUE THREAD

**Issue by vevota** [MedicodiBiscotti/biscottiHUD#5]
Basically the title. They go over each other.

**Comment by MedicodiBiscotti** [comment]
Thank you pointing it out! What happened was that I though Valve added a new meter for the gas can whileit was actually for the phlog. So when I moved that I didn't realize it would land on top of the jetpack.
It's fixed now even though it took me 16 days to notice the issue :)
